// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHCiysB6r-DWFzLdhgDwyaArQYrd6m9E',
    appId: '1:158650970118:web:f88cfe48990a48c3a8d387',
    messagingSenderId: '158650970118',
    projectId: 'mobile-looms',
    authDomain: 'mobile-looms.firebaseapp.com',
    storageBucket: 'mobile-looms.firebasestorage.app',
    measurementId: 'G-EQGNFJ16DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qXlSaXubtupxLbHuJukH_aR8lEyVseE',
    appId: '1:158650970118:android:d1158027b16e51f1a8d387',
    messagingSenderId: '158650970118',
    projectId: 'mobile-looms',
    storageBucket: 'mobile-looms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwW37t_BVPYW-nOq1l8ghaloQKlEwMzJ8',
    appId: '1:158650970118:ios:59cd212ceb9ff971a8d387',
    messagingSenderId: '158650970118',
    projectId: 'mobile-looms',
    storageBucket: 'mobile-looms.firebasestorage.app',
    iosBundleId: 'com.example.mobileLooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwW37t_BVPYW-nOq1l8ghaloQKlEwMzJ8',
    appId: '1:158650970118:ios:59cd212ceb9ff971a8d387',
    messagingSenderId: '158650970118',
    projectId: 'mobile-looms',
    storageBucket: 'mobile-looms.firebasestorage.app',
    iosBundleId: 'com.example.mobileLooms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYHCiysB6r-DWFzLdhgDwyaArQYrd6m9E',
    appId: '1:158650970118:web:4fb6ec306af59fafa8d387',
    messagingSenderId: '158650970118',
    projectId: 'mobile-looms',
    authDomain: 'mobile-looms.firebaseapp.com',
    storageBucket: 'mobile-looms.firebasestorage.app',
    measurementId: 'G-K35S1X6GTW',
  );
}
